### ISSUE TITLE
rename addhourstoservertime option to make clear that it supports negative values

### ISSUE THREAD

**Issue by dvdcd** [NiklasEi/CalendarEvents#14]
Currently, the addhourstoservertime config option only allows for time zones that are behind the desired timezone. In my situation my server is ahead of the desired timezone and i would like to subtract from the server's time to reach the desired time.

**Comment by dvdcd** [comment]
On second look, i'm an idiot and didn't offset the timezone enough. I would still suggest changing the name of the addhourstoservertime option to timezoneoffset or something like that and say that the value also supports subtracting from the server's timezone.

Also the /calendarevents list command doesn't take the timezone offset into account when listing the next time a event will be called

**Comment by NiklasEi** [comment]
Thanks for the issue, I will rename the option then.


> Also the /calendarevents list command doesn't take the timezone offset into account when listing the next time a event will be called

Could you open a separate issue for this, please? :slightly_smiling_face:
