### ISSUE TITLE
countdown

### ISSUE THREAD

**Issue by yueyinqiu** [NiklasEi/CalendarEvents#19]
it's a nice plugin, but i have no idea how to configure a countdown before issuing some other commands.

 is it possible to do this just with the plugin? or maybe i have to write another plugin with the provided api?

**Comment by NiklasEi** [comment]
You can configure a countdown, but the maximum frequency is one event per minute (always the first second of the minute).

**Comment by yueyinqiu** [comment]
got it, thanks
