### ISSUE TITLE
placeholder

### ISSUE THREAD

**Issue by D3BoxOfficiel** [NiklasEi/CalendarEvents#7]
can use placeholder or mvdw to display the remaining time of the next event (in months, weeks, days, hours, minutes, seconds)

**Comment by NiklasEi** [comment]
I did not implement anything for months and weeks jet, but you have several placeholders to choose from.
"%calendarevents_until:myEventLabel%" returns time in `d h min s`
"%calendarevents_until-s:myEventLabel%" returns time in `s`
"%calendarevents_until-min:myEventLabel%" returns time in `min`
"%calendarevents_until-h:myEventLabel%" returns time in `h`
"%calendarevents_until-d:myEventLabel%" returns time in `d`

If all events of the given label are in the past, the placeholder will be resolved as "never"
